### ISSUE TITLE
Abstracting data sources into separate plugins

### ISSUE THREAD

**Issue by vishthemenon** [CitationGecko/citation-network-explorer#35]
Objective: A uniform API/data structure for accepting data sources
Motivation: Makes it easier to create "data-source" plugins that can be maintained separate from the main repository. Also makes it easier for people to integrate private data sources by creating a plugin.

**Comment by vot** [comment]
Hi @vishthemenon,

Thanks for raising the issue.

There's some work currently being reviewed (#33); it addresses part of your request by introducing HTTP API layer. This is then used as data source in the application.
I'm currently investigating an issue of extra latency this creates.
You can expect some updates to the interfaces that should standardise the data and improve overall performance.

**Comment by vishthemenon** [comment]
@vot Excellent PR!

I personally like that approach of decoupling concerns. Personally, I would take 1 step further and decouple the UI and API further. This makes the repo cleaner and also encourages more user facing implementations of the API (ie. Desktop app, citation alert etc.). However, it is not as high priority as some other householding, refactoring stuff that you have already kicked off in that PR. Cheers!

PS. Having exams right now. Will try to work on some issues in a few weeks time when it is all over.

**Comment by bjw49** [comment]
Yes, still need to do a bit more decoupling as the CrossRef, Microsoft and OADOI calls are all tangled up in each other at the moment but should be fairly straightforward to separate and allow for  extendable modularity.
