### ISSUE TITLE
Participation to the Workshop on Open Citations

### ISSUE THREAD

**Issue by essepuntato** [CitationGecko/citation-network-explorer#37]
Hi @bjw49 

I think a workshop I'm co-organising could be of interest for your research on improving scholarly communication and your supporters. It is the Workshop on Open Citations (3-5 Sept. Bologna, Italy). More info at https://workshop-oc.github.io/. Deadline for applications: **20 May**.

I apologise for writing it here, but it is quite impossible to find your email on the Web.

Have a nice day :-)

S.

**Comment by bjw49** [comment]
Thanks for the reminder! I was planning to apply, just haven't found the time yet. Will hopefully get to it tonight.
