### ISSUE TITLE
Pagination of Zotero collection requests

### ISSUE THREAD

**Issue by bjw49** [CitationGecko/citation-network-explorer#72]
At the moment, we only retrieve the first 100 of a users Zotero collections as their api only allows for 100 per call. Need to submit multiple requests to get full list.

Most users probably won't have >100 collections so not a priority.

**Comment by vot** [comment]
Fixed in this commit:
https://github.com/CitationGecko/citation-network-explorer/commit/6ad4c95719092242dc5b0271b2986a94dd5a0d0d

**Comment by bjw49** [comment]
Thanks Vot!

**Comment by bjw49** [comment]
merged into master
